"""
AUTO-GENERATED BY KEYCODE
"""

class Codes:
    class slimebones:
        class wsbus:
            class bus:
                class service:
                    bus = "slimebones.wsbus.bus.service.bus"
            class message:
                class message:
                    subscribe = "slimebones.wsbus.message.message.subscribe"
                    subscribed = "slimebones.wsbus.message.message.subscribed"
                class error:
                    message = "slimebones.wsbus.message.error.message"
